// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var loginService;

  loginService = void 0;

  angular.module('solrpressApp').factory('AuthServerProvider', loginService = function($http, localStorageService) {
    return {
      login: function(credentials) {
        var data;
        data = void 0;
        data = 'j_username=' + encodeURIComponent(credentials.username) + '&j_password=' + encodeURIComponent(credentials.password) + '&_spring_security_remember_me=' + credentials.rememberMe + '&submit=Login';
        return $http.post('api/authentication', data, {
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
          }
        }).success(function(response) {
          localStorageService.set('token', btoa(credentials.username + ':' + credentials.password));
          return response;
        });
      },
      logout: function() {
        localStorageService.clearAll();
        $http.post('api/logout');
      },
      getToken: function() {
        var token;
        token = void 0;
        token = localStorageService.get('token');
        return token;
      },
      hasValidToken: function() {
        var token;
        token = void 0;
        token = this.getToken();
        return !!token;
      }
    };
  });

}).call(this);
