// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Account;

  Account = void 0;

  angular.module('solrpressApp').factory('Account', Account = function($resource) {
    return $resource('api/account', {}, {
      get: {
        method: 'GET',
        params: {},
        isArray: false,
        interceptor: {
          response: function(response) {
            return response;
          }
        }
      }
    });
  });

}).call(this);
