// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('Activate', function($resource) {
    return $resource('api/activate', {}, {
      get: {
        method: 'GET',
        params: {},
        isArray: false
      }
    });
  });

}).call(this);
