// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('Password', function($resource) {
    return $resource('api/account/change_password', {}, {});
  });

}).call(this);
