// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('Register', function($resource) {
    return $resource('api/register', {}, {});
  });

}).call(this);
