// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('Sessions', function($resource) {
    return $resource('api/account/sessions/:series', {}, {
      getAll: {
        method: 'GET',
        isArray: true
      }
    });
  });

}).call(this);
