# Generated by CoffeeScript 1.9.0
'use strict'
angular.module('solrpressApp').controller 'LanguageController', ($scope, $translate, Language) ->

  $scope.changeLanguage = (languageKey) ->
    $translate.use languageKey
    return

  Language.getAll().then (languages) ->
    $scope.languages = languages
    return
  return
