// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('Language', function($q, $http, $translate, LANGUAGES) {
    var self;
    self = void 0;
    self = this;
    return {
      getCurrent: function() {
        var deferred, language;
        deferred = void 0;
        language = void 0;
        deferred = $q.defer();
        language = $translate.storage().get('NG_TRANSLATE_LANG_KEY');
        if (language == null) {
          language = 'en';
        }
        deferred.resolve(language);
        return deferred.promise;
      },
      getBy: function(language) {
        var deferred;
        deferred = void 0;
        deferred = $q.defer();
        deferred.resolve(LANGUAGES);
        return deferred.promise;
      }
    };
  }).constant('LANGUAGES', ['en', 'fr']);

}).call(this);
