// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').factory('LogsService', function($resource) {
    return $resource('api/logs', {}, {
      findAll: {
        method: 'GET',
        isArray: true
      },
      changeLevel: {
        method: 'PUT'
      }
    });
  });

}).call(this);
