// Generated by CoffeeScript 1.9.0
'use strict';
angular.module('solrpressApp').config(function($stateProvider) {
  $stateProvider.state('logout', {
    parent: 'account',
    url: '/logout',
    data: {
      roles: []
    },
    views: {
      'content@': {
        templateUrl: 'scripts/app/main/main.html',
        controller: 'LogoutController'
      }
    }
  });
});
