// Generated by CoffeeScript 1.8.0
"use strict";
var solrpressApp;

solrpressApp = angular.module("solrpressApp", ['ngTouch', 'ngCookies', 'ngAria', 'ngSanitize', 'ui.router', 'ngResource', 'LocalStorageModule', 'tmh.dynamicLocale', 'pascalprecht.translate', 'ui.grid', 'ui.grid.paging', 'ui.grid.resizeColumns', 'ui.grid.pinning', 'ui.grid.selection', 'ui.grid.moveColumns', 'ui.utils', 'ui.bootstrap', 'angularMoment', 'angularFileUpload', 'ngCacheBuster']);

solrpressApp.config(function($stateProvider, $urlRouterProvider, $httpProvider, $locationProvider, $translateProvider, tmhDynamicLocaleProvider, httpRequestInterceptorCacheBusterProvider, USER_ROLES) {
  var defaultHeaders;
  httpRequestInterceptorCacheBusterProvider.setMatchlist([/.*rest.*/], true);
  $.material.init();
  $locationProvider.html5Mode(true).hashPrefix('!');
  $translateProvider.preferredLanguage('en');
  $httpProvider.defaults.xsrfCookieName = 'XSRF-TOKEN';
  $httpProvider.defaults.xsrfHeaderName = 'X-XSRF-TOKEN';
  $httpProvider.defaults.withCredentials = false;
  defaultHeaders = {
    'Content-Type': 'application/json',
    'Accept-Language': 'en',
    'X-Requested-With': 'XMLHttpRequest'
  };
  $httpProvider.defaults.headers["delete"] = defaultHeaders;
  $httpProvider.defaults.headers.patch = defaultHeaders;
  $httpProvider.defaults.headers.post = defaultHeaders;
  $httpProvider.defaults.headers.put = defaultHeaders;
  $httpProvider.defaults.headers.get = defaultHeaders;
  $urlRouterProvider.otherwise('/');
  $stateProvider.state("/register", {
    templateUrl: "views/register.html",
    controller: "RegisterController",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  }).state("/activate", {
    templateUrl: "views/activate.html",
    controller: "ActivationController",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  }).state("/login", {
    templateUrl: "views/login.html",
    controller: "LoginController",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  }).state("/error", {
    templateUrl: "views/error.html",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  }).state("/settings", {
    templateUrl: "views/settings.html",
    controller: "SettingsController",
    access: {
      authorizedRoles: [USER_ROLES.user]
    }
  }).state("/password", {
    templateUrl: "views/password.html",
    controller: "PasswordController",
    access: {
      authorizedRoles: [USER_ROLES.user]
    }
  }).state("/sessions", {
    templateUrl: "views/sessions.html",
    controller: "SessionsController",
    resolve: {
      resolvedSessions: [
        "Sessions", function(Sessions) {
          return Sessions.get();
        }
      ]
    },
    access: {
      authorizedRoles: [USER_ROLES.user]
    }
  }).state("/tracker", {
    templateUrl: "views/tracker.html",
    controller: "TrackerController",
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/metrics", {
    templateUrl: "views/metrics.html",
    controller: "MetricsController",
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/health", {
    templateUrl: "views/health.html",
    controller: "HealthController",
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/configuration", {
    templateUrl: "views/configuration.html",
    controller: "ConfigurationController",
    resolve: {
      resolvedConfiguration: [
        "ConfigurationService", function(ConfigurationService) {
          return ConfigurationService.get();
        }
      ]
    },
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/logs", {
    templateUrl: "views/logs.html",
    controller: "LogsController",
    resolve: {
      resolvedLogs: [
        "LogsService", function(LogsService) {
          return LogsService.findAll();
        }
      ]
    },
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/audits", {
    templateUrl: "views/audits.html",
    controller: "AuditsController",
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/logout", {
    templateUrl: "views/main.html",
    controller: "LogoutController",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  }).state("/docs", {
    templateUrl: "views/docs.html",
    access: {
      authorizedRoles: [USER_ROLES.admin]
    }
  }).state("/home", {
    templateUrl: "views/main.html",
    controller: "MainController",
    access: {
      authorizedRoles: [USER_ROLES.all]
    }
  });
  $translateProvider.useStaticFilesLoader({
    prefix: "i18n/",
    suffix: ".json"
  });
  $translateProvider.preferredLanguage("en");
  $translateProvider.useCookieStorage();
  tmhDynamicLocaleProvider.localeLocationPattern("bower_components/angular-i18n/angular-locale_{{locale}}.js");
  tmhDynamicLocaleProvider.useCookieStorage("NG_TRANSLATE_LANG_KEY");
}).run(function($rootScope, $location, $http, AuthenticationSharedService, Session, USER_ROLES) {
  $rootScope.authenticated = false;
  $rootScope.$on("$stateChangeStart", function(event, next) {
    $rootScope.isAuthorized = AuthenticationSharedService.isAuthorized;
    $rootScope.userRoles = USER_ROLES;
    AuthenticationSharedService.valid(next.access.authorizedRoles);
  });
  $rootScope.$on("event:auth-loginConfirmed", function(data) {
    var search;
    $rootScope.authenticated = true;
    if ($location.path() === "/login") {
      search = $location.search();
      if (search.redirect !== undefined) {
        $location.path(search.redirect).search("redirect", null).replace();
      } else {
        $location.path("/").replace();
      }
    }
  });
  $rootScope.$on("event:auth-loginRequired", function(rejection) {
    var redirect;
    Session.invalidate();
    $rootScope.authenticated = false;
    if ($location.path() !== "/" && $location.path() !== "" && $location.path() !== "/register" && $location.path() !== "/activate" && $location.path() !== "/login") {
      redirect = $location.path();
      $location.path("/login").search("redirect", redirect).replace();
    }
  });
  $rootScope.$on("event:auth-notAuthorized", function(rejection) {
    $rootScope.errorMessage = "errors.403";
    $location.path("/error").replace();
  });
  $rootScope.$on("event:auth-loginCancelled", function() {
    $location.path("");
  });
}).run(function($rootScope, $state) {
  $rootScope.websocketSocket = atmosphere;
  $rootScope.websocketSubSocket;
  $rootScope.websocketTransport = "websocket";
  $rootScope.websocketRequest = {
    url: "websocket/activity",
    contentType: "application/json",
    transport: $rootScope.websocketTransport,
    trackMessageLength: true,
    reconnectInterval: 5000,
    enableXDR: true,
    timeout: 60000
  };
  $rootScope.websocketRequest.onOpen = function(response) {
    $rootScope.websocketTransport = response.transport;
    $rootScope.websocketRequest.sendMessage();
  };
  $rootScope.websocketRequest.onClientTimeout = function(r) {
    $rootScope.websocketRequest.sendMessage();
    setTimeout((function() {
      $rootScope.websocketSubSocket = $rootScope.websocketSocket.subscribe($rootScope.websocketRequest);
    }), $rootScope.websocketRequest.reconnectInterval);
  };
  $rootScope.websocketRequest.onClose = function(response) {
    if ($rootScope.websocketSubSocket) {
      $rootScope.websocketRequest.sendMessage();
    }
  };
  $rootScope.websocketRequest.sendMessage = function() {
    if ($rootScope.websocketSubSocket.request.isOpen) {
      if ($rootScope.account != null) {
        $rootScope.websocketSubSocket.push(atmosphere.util.stringifyJSON({
          userLogin: $rootScope.account.login,
          page: $state.current.templateUrl
        }));
      }
    }
  };
  $rootScope.websocketSubSocket = $rootScope.websocketSocket.subscribe($rootScope.websocketRequest);
  $rootScope.$on("$stateChangeSuccess", function(event, next, current) {
    $rootScope.websocketRequest.sendMessage();
  });
});
