// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('solrpressApp').config(function($stateProvider) {
    $stateProvider.state('admin', {
      abstract: true,
      parent: 'site'
    });
  });

}).call(this);
